### ISSUE TITLE
performance improvements?

### ISSUE THREAD

**Issue by kodonnell** [deoplete-plugins/deoplete-dictionary#1]
I tried this out and completion for a 100k dictionary is surprisingly slow - say half a second. I quickly hacked something where I did the filtering in `gather_candidates` (something like `return [{'word': w} for w in candidates if w.startswith(context['complete_str'])`) and it's nearly instant and seems to work fine. This surprises me, as I thought `matcher_head` would be doing the same thing.

Does anyone
1. see why the current implementation is so much slower?
2. object to having an implementation similar to the above as a PR?

**Comment by Shougo** [comment]
I need to reproduce the problem.
Please upload the dictionary to test and vimrc with minimal config.

If not, I will ignore your report.

**Comment by kodonnell** [comment]
Just the basics - install deoplete and deoplete-dictionary:

`init.vim`: 

```
let g:plug_timeout=1000
if empty(glob('~/.config/nvim/autoload/plug.vim'))
  silent !curl -fLo ~/.config/nvim/autoload/plug.vim --create-dirs
    \ https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
  autocmd VimEnter * PlugInstall --sync | source $MYVIMRC
endif
call plug#begin()
    Plug 'Shougo/deoplete.nvim', { 'do': ':UpdateRemotePlugins' }
    Plug 'deoplete-plugins/deoplete-dictionary'
call plug#end()
let g:deoplete#enable_at_startup = 1
setlocal dictionary+=/usr/share/dict/british-english
call deoplete#custom#source('dictionary', 'matchers', ['matcher_head'])
call deoplete#custom#source('dictionary', 'sorters', [])
call deoplete#custom#source('dictionary', 'min_pattern_length', 4)
```

dictionary: `sudo apt-get install wbritish`

steps: type `elep` ... takes about half a second for menu to appear. As above, should be nearly instant.

**Comment by Shougo** [comment]
OK.  I have reproduced.
I get the reason.  Please wait.

**Comment by Shougo** [comment]
Fixed.  Please update deoplete to the latest.

**Comment by kodonnell** [comment]
Confirmed. Thanks.
