### ISSUE TITLE
completion with upper case

### ISSUE THREAD

**Issue by kodonnell** [deoplete-plugins/deoplete-dictionary#2]
With `ignorecase` on, when I type `Elep` I correctly see `elephant` as an option. However, when I complete with it, `elephant` is used, i.e. my case is removed. Expected behaviour is completing as `Elephant`.

Am I missing an option, or is this something deoplete doesn't support? For now I've just quickly added it as part of my hack for #1, and it works as expected - basically, `return [{'word': start + w[len(start):]'} ...`.

**Comment by Shougo** [comment]
I have added `converter_case` for it.

**Comment by kodonnell** [comment]
Thanks. For others - see [here](https://github.com/Shougo/deoplete.nvim/commit/378feff8772d0e9f9ef2c94284947f3666576500) for reference.
